config/routes.rb
Rails.application.routes.draw do
  get 'footer/index'
  get 'articles/image_view_hero'       ## foo is the name of your controller
 get 'articles/image_view_optional'
 get 'articles/pageResults'
  resources :articles

  

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
    @previewArticles = Article.all.select("id,title,publication_date,author,hero_image_filename,content_body").order("id desc")
    @articles = Article.order(publication_date: :desc).paginate(page: params[:mpage], :per_page => 3) 
    @articleResults = Article.all.select("id,title").order("id desc")
end
  
def new
    @articleResults = Article.all
end
  
def create
    @article = Article.new(article_params)
    @article.publication_date = Time.zone.now
    if params[:article][:hero_image]
        @article.hero_image = params[:article][:hero_image].read
        @article.hero_image_filename = params[:article][:hero_image].original_filename
        @article.hero_image_contenttype = params[:article][:hero_image].content_type
    end
    if params[:article][:optional_image]
        @article.optional_image = params[:article][:optional_image].read
        @article.optional_image_filename = params[:article][:optional_image].original_filename
        @article.optional_image_contenttype = params[:article][:optional_image].content_type
    end
    @article.save()
    @articleResults = Article.all.select("id,title").order("id desc")
    redirect_to @article
      
end

def show
    @article = Article.find(params[:id])  
    @articleResults = Article.all.select("id,title").order("id desc")
end
   
def image_view_hero
    @article = Article.find(params[:id]) 
    send_data(@article.hero_image, :filename => @article.hero_image_filename, :type => @article.hero_image_contenttype, :disposition => "inline")
end

def image_view_optional
    @article = Article.find(params[:id]) 
    send_data(@article.optional_image, :filename => @article.optional_image_filename, :type => @article.optional_image_contenttype, :disposition => "inline")
end

def edit
    @article = Article.find(params[:id])
    @articleResults = Article.all.select("id,title").order("id desc")
end
    
def update
    @articleOld = Article.find(params[:id])
    @article =  Article.new(article_params)
    @article.publication_date = Time.zone.now
    if params[:article][:hero_image]
        @article.hero_image = params[:article][:hero_image].read
        @article.hero_image_filename = params[:article][:hero_image].original_filename
        @article.hero_image_contenttype = params[:article][:hero_image].content_type
    else
        @article.hero_image = @articleOld.hero_image
        @article.hero_image_filename =  @articleOld.hero_image_filename
        @article.hero_image_contenttype =  @articleOld.hero_image_contenttype
    end
    if params[:article][:optional_image]
       @article.optional_image = params[:article][:optional_image].read
       @article.optional_image_filename = params[:article][:optional_image].original_filename
       @article.optional_image_contenttype = params[:article][:optional_image].content_type
    else
       @article.optional_image = @articleOld.optional_image
       @article.optional_image_filename =  @articleOld.optional_image_filename
       @article.optional_image_contenttype =  @articleOld.optional_image_contenttype
    end
    @articleOld.destroy
    @article.save()
    @articleResults = Article.all.select("id,title").order("id desc")
    redirect_to @article
   end
   
def destroy
    @article = Article.find(params[:id])
    @article.destroy
    @articleResults = Article.all.select("id,title").order("id desc")
    redirect_to articles_path
  end
 
def pageResults
    @articleResults = Article.all.select("id,title").order("id desc")
    redirect_to articles_path
end

private
def article_params
    params.require(:article).permit(:title, :author, :category, :hero_image, :hero_image_filename, :hero_image_contenttype, :optional_image, :optional_image_filename, :optional_image_contenttype, :content_body)
end


end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def index
      @articles1 = Article.paginate(page: params[:page], :per_page => 3) 
  end
  
  def new
  end
  
  def show
    @article = Article.find(params[:id])
    @articles1 = Article.paginate(page: params[:page], :per_page => 3)  
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
   attr_reader :day

    def day_ordinal_suffix(day)
       if day == 11 or day == 12
         return "th"
       else
         case day % 10
         when 1 then return "st"
         when 2 then return "nd"
         when 3 then return "rd"
         else return "th"
         end
       end
   end
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div style= "padding-left:15px;">
<%= form_for(:article, :url=>{:action=>'update'},   :method => :PUT, :html=>{:multipart=>true}) do |f|%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :heroimage %><br>
    <%= f.file_field :hero_image %>
  </p>
  <p>
    <%= f.label :optionalimage %><br>
    <%= f.file_field :optional_image %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content_body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div style= "padding-left:15px;width:1000px;">
    <B><%= link_to 'Create article', new_article_path %></B> 
    <% previewArticle = @previewArticles[rand(0...@previewArticles.size)] %>
    <% if not previewArticle.nil?  %>
        <table>
            <tr>
                <td><H3><%= link_to previewArticle.title, article_path(previewArticle) %></H3></td> 
            </tr>
            <tr>
                <td><%= previewArticle.publication_date.strftime("%A %B #{previewArticle.publication_date.day.ordinalize}, %Y")  %> | <%= previewArticle.author %></td></tr>
                  <% if not previewArticle.hero_image_filename.nil?  %>
                     <tr><td><img  src="<%= url_for(:controller => "articles", :action => "image_view_hero", :id => previewArticle.id) %>"  width="400"  height="200" /></td></tr>
                  <%end%>
            <tr><td><%= previewArticle.content_body %></td></tr>
        </table><br>
    <%end%>

<div style= "padding-left:50px;">
    <% @articles.each do |article| %>
        <table>
            <tr>
                <td><H3><%= link_to article.title, article_path(article) %></H3></td>
            </tr>
            <tr><td><%= article.content_body %></td></tr>
            <td><B><%= link_to 'Edit article', edit_article_path(article) %> </B> 
                <B><%= link_to 'Delete article', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></B>
            </td>
        </table><br>
    <% end %>
</div>

<%= will_paginate @articles, :param_name => 'mpage'%>
</div> 

app/views/articles/new.html.erb
<div style= "padding-left:15px;">
<%= form_for(:article, :url=>{:action=>'create'}, :html=>{:multipart=>true}) do |f|%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :heroimage %><br>
    <%= f.file_field :hero_image %>
  </p>
  <p>
    <%= f.label :optionalimage %><br>
    <%= f.file_field :optional_image %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content_body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div style= "padding-left:15px;">
<table colspan="3" width="400" height="150">
  <tr><td><H2><%= @article.title %></H2></td></tr>
  <tr><td><%= @article.publication_date.strftime("%A %B #{@article.publication_date.day.ordinalize}, %Y")  %> | <%= @article.author %></td></tr>
  <tr><td>
    <% if not @article.hero_image_filename.nil?  %>
       <img src="<%= url_for(:controller => "articles", :action => "image_view_hero", :id => @article.id) %>"  width="400"  height="200" />
    <%end%>
 </td>
 <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
 <td>
     <% if not @article.optional_image_filename.nil?  %>
      <img src="<%= url_for(:controller => "articles", :action => "image_view_optional", :id => @article.id) %>"  width="400"  height="200"/>
     <% end%>
   </td>
   </tr>
 <tr><td>
  <table  width="500">
   <tr><td><%= @article.content_body %></td></tr>
   <% if not @articleResults.nil?  %>
      <% $i = 0 %>
      <% unless @articleResults.size >= 4 %>
        <% $num = @articleResults.size %>
      <%else %>
        <% $num = 4 %>
      <%end%>
   <tr> 
    <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
    <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
    <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
   </tr>

<%end%> 
  </table>
  </td> 
 <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
 <td><table  width="400">
  <th><h3>Related links </h3></th>
   <% if not @articleResults.nil?  %>
     <% $i = 0 %>
     <% unless @articleResults.size >= 4 %>
       <% $num = @articleResults.size %>
     <%else%>
       <% $num = 4 %>
     <%end%>
     <% while $i < $num  do %>
           <% article = @articleResults[rand(0...@articleResults.size)] %>
         <tr>
           <td><%= link_to article.title, article_path(article) %></td>
           <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
           <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
         </tr>
         <% $i +=1 %>
     <% end %>
   <% end %>
  </table></td><tr></tr>
</table>
<%= link_to 'Back', articles_path %>
</div>

app/views/footer/index.html.erb
<!-- Site footer -->
<div class="bottom">
    <%= will_paginate @articles1 %>
    <div class="container">
        
            <% @articles1.each do |article| %>
        <div class="col-md-4">
           <tr>
      <td><%= link_to article.title, article_path(article) %></td> </tr>
      <tr><td><%= article.author %></td></tr>
      <tr><td><%= article.category %></td></tr>
      <tr><td><%= article.content_body %></td></tr>
        </div>
        
          <% end %>
    </div>
    



            

  
</div>

app/views/footer/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
 
   <p>
    <%= f.label :heroimage %><br>
    <%= f.file_field :hero_image %>
  </p>
  
    <p>
    <%= f.label :optionalimage %><br>
    <%= f.file_field :optional_image %>
  </p>

 <p>
    <%= f.label :content %><br>
    <%= f.text_field :content_body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArticlesApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
    		<link href="http://fonts.googleapis.com/css?family=Cookie|Open+Sans:400,700" rel="stylesheet" />
    		<!-- Include AngularJS from Google's CDN -->
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>


    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
	<body >



    <%= render 'shared/navigation_bar' %> 
    <%= yield %>
    <%= render 'shared/footer_bar' %> 
    
    

  </body>
</html>

app/views/shared/_footer_bar.html.erb
<!-- Site footer -->
<div class="bottom" >
    <table colspan ="2" class="whatToread">
      <tr><td style="width:80%">
        <div>
            <table colspan="1" style="width:80%" ><tr><td><h4> What to Read Next <h4></td></tr>
            </table>
        </div>
      </td>
      <td style="width:17%">
        <div class="" style="align:right">
            <table colspan="3" >
              <tr>
              <td> 
                  <%= link_to image_tag("left_arrow.gif", {:controller => "articles", :action => 'pageResults'}) %>
              </td>
              <td><%= image_tag("vertical_line.gif")%></td>
              <td align="rigth"><%= link_to image_tag("right_arrow.gif", {:controller => "articles", :action => 'pageResults'}) %>
              </td>
              </tr>
            </table>
        </div>
      </td>
      </tr>
    </table>
    <div class="container" style="width:100%;" id="displayFooter">
        <% if not @articleResults.nil?  %>
           <% $i = 0 %>
           <% unless @articleResults.size >= 4 %>
             <% $num = @articleResults.size %>
           <%else%>
             <% $num = 4 %>
           <%end%>
           <% while $i < $num  do %>
                <% article = @articleResults[rand(0...@articleResults.size)] %>
                <div class="col-md-3" >
                    <table>
                        <tr><td> <%= link_to image_tag(url_for(:controller => "articles", :action => "image_view_hero", :id => article.id), :size => "260x180"), {:action => 'show', :id => article.id}%>
                        </td></tr>  
                    </table>
                    <tr><td><%= link_to article.title, article_path(article) %></td></tr>
                </div>
                <% $i +=1 %>
                <%end%>
           <%end%>         
    </div>
</div>

app/views/shared/_navigation_bar.html.erb
<div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Gale Exercise
                    </a>
                </li>
                <li>
                   <%= link_to 'Dashboard', articles_path %>
                </li>
                <li>
                     <%= link_to 'Overview', articles_path %>
                </li>
                <li>
                    <%= link_to 'About', articles_path %>
                </li>
                <li>
                    <%= link_to 'Services', articles_path %>
                </li>
                <li>
                    <%= link_to 'Contact', articles_path %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>